spring.application.name=outsera
server.port=8081
spring.datasource.url=jdbc:h2:mem:raspberrydb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

app.movies.csv-filename=movielist.csv

springdoc.swagger-ui.path=/swagger-ui.html

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.file.name=logs/app-movies.log
br.com.teste.outsera=INFO
